version: "3.7"
services:
  web:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/fdz
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - db:/data/db
    expose:
      - "27017:27017"

volumes:
  db:
